# Generated by Django 5.0.6 on 2024-07-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_num',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
