# Generated by Django 5.0.6 on 2024-07-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_profile_mobile_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_num',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
