# Generated by Django 5.0.6 on 2024-08-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_type_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='type',
        ),
    ]
