# Generated by Django 5.0.6 on 2024-08-17 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_favorites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('user', 'post')},
        ),
        migrations.AddField(
            model_name='favorites',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='favorite',
        ),
    ]
