# Generated by Django 5.0.6 on 2024-11-15 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_message_options_rename_message_message_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rental')),
            ],
        ),
        migrations.CreateModel(
            name='RentalLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.rental')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('rental', 'user')},
            },
        ),
    ]
