# Generated by Django 5.0.6 on 2024-11-20 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rateowner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_rates_received', to=settings.AUTH_USER_MODEL)),
                ('rate_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_rates_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
